#!/bin/bash
# Auto Script for Multi OS By Mtknetwork 2022
RED='\033[01;31m';
RESET='\033[0m';
GREEN='\033[01;32m';
WHITE='\033[01;37m';
YELLOW='\033[00;33m';

echo -e "                $GREEN Choose Your Category $RESET"
echo '                                                              
    ██████╗ ███████╗██╗  ██╗████████╗███████╗██████╗        
    ██╔══██╗██╔════╝╚██╗██╔╝╚══██╔══╝██╔════╝██╔══██╗       
    ██║  ██║█████╗   ╚███╔╝    ██║   █████╗  ██████╔╝       
    ██║  ██║██╔══╝   ██╔██╗    ██║   ██╔══╝  ██╔══██╗       
    ██████╔╝███████╗██╔╝ ██╗   ██║   ███████╗██║  ██║       
    ╚═════╝ ╚══════╝╚═╝  ╚═╝   ╚═╝   ╚══════╝╚═╝  ╚═╝       
'     
PS3='Choose or Type a Plan: '
options=("PREMIUM" "VIP" "PRIVATE" "NONE" "Quit")
select opt in "${options[@]}"; do
case "$opt,$REPLY" in
PREMIUM,*|*,PREMIUM) 
echo "";
echo -e "                $GREEN 1) PREMIUM Selected$RESET";
sleep 2s
clear
	
wget -O mediatek-prem.sh "http://script.mediatekvpn.com/ssh/mediatekvpn/mediatek-prem.sh" && 
chmod +x ~/mediatek-prem.sh && sed -i -e 's/\r$//' ~/mediatek-prem.sh && ./mediatek-prem.sh

echo "";
break ;;
VIP,*|*,VIP) 
echo "";
echo -e "                $GREEN 2) VIP Selected$RESET";
sleep 2s
clear

wget -O mediatek-vip.sh "http://script.mediatekvpn.com/ssh/mediatekvpn/mediatek-vip.sh" && 
chmod +x ~/mediatek-vip.sh && sed -i -e 's/\r$//' ~/mediatek-vip.sh && ./mediatek-vip.sh

break ;;
PRIVATE,*|*,PRIVATE) 
echo "";
echo -e "                $GREEN 3) PRIVATE Selected$RESET";
sleep 2s
clear

wget -O mediatek-pri.sh "http://script.mediatekvpn.com/ssh/mediatekvpn/mediatek-pri.sh" && 
chmod +x ~/mediatek-pri.sh && sed -i -e 's/\r$//' ~/mediatek-pri.sh && ./mediatek-pri.sh

echo "";
break ;;
NONE,*|*,NONE) 
echo "";
echo -e "                $GREEN 2) NONE Selected$RESET";
sleep 2s
clear

wget 

echo "";
break ;;
Quit,*|*,Quit) echo -e " $RED   Installation Cancelled!$RESET";
echo -e "                $RED   Rebuild your vps and correct the process.$RESET";
rm installer.sh
exit;
break ;; *)
echo -e "                $RED   Invalid: Just choose what you want$RESET";
esac
done
